language: java
jdk:
- oraclejdk8
- oraclejdk7
os:
- linux
branches:
  only:
  - master
  - dev
sudo: required
after_success:
- mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/jacoco/jacoco.xml -DprojectToken=$CODACY_PROJECT_TOKEN -DapiToken=$CODACY_API_TOKEN -DcodacyApiBaseUrl=https://api.codacy.com
env:
  global:
  - secure: "E1EX1ML4f34IFqUf1EcONTCiv98QMFkvm5dMGDoAIQ1PPcTcvVetP0kOFFBzrrsGHYIgGQXElyR172nNl3akRiIEABSUhaR9zctEFG2Bt/6ETLevJoyNFhK8AjkzufkFJQrIO6LbTSfTIbsWwI8HOp5TJXxvzo6SBXkW7vkfnA80w9AMF8nqmNxr359nbGsI9lxNDBYpW4ZLWCeoKZFnfTLs4jrjZFHek2NQ1LjLP43BoeB4J9KPd2bCXmbZL5n8P7jIfaL7H7CJbG8CBPOKY88TDDW65r+l47w7wJxTh59hIYqEoAT1m/z33aJ2CFGYawpN9B+XwsSAJgIyYgJ2r6bsO5hxL3tf5YMcB+otDe3TQ1bXOeTw+QOJ48p6pTBeDsVvgjBAQIuVBv7HbMSggN/85ylB4Q+XDzrixnd69H1VN+udLql6hvNYFAvjIY0hd2ZWuppuIlxkiHf7dYoMiQkJcHrgFluH+soQfK1idEzvU7Lf0KkoGvPbVA3NRvY4obvgZYLI8LIGBBcObGgphqGNpIJwt/tCz2UQhVUd8DdpiRrZCKKH7+PvNGD3vV9ynw4hceKmDOz9tug0ELBjc280LoJpEhB1GQ15D23vJQPxGBpNXK6/mj7yJRMly8lSJcn5WipIqfdJGIodvs11kPsvcegzsid7iignuhUDrhQ="
  - secure: "Lfs7X0gzKIWrvrttAi6DR494QURAdhOW49W9iCUtQcFtesuQ6vxAfqTrpcO8KrURhMP6RB0S8izldet4G4/kLmeDGD1faBOL0hST1sBtZxIH7RW9tgztD9dqApPv90+pkyBk1Kln83MJ7n9V2+X4fL01Ji9D1QqTR9p2rCaWupbalz1YwQpXCHUd9qU9i1grqNLsI9W2ES03jNspO1zo5iSN4VhOMkyvydM1rUj8Ej0o44n522Goxldu43ssKosftkA6V/XPcBjfKrslLTgCEyMJGuiCmfivI0VOkt3gqVcm00C1sJ/ImUjJZgwknUmikzbAlvDFGG8plBpdMBCH+rL25NpOobw1BqvOTvnTnv3MFuG3zE3JOSI+Dc59vFhbC6gPHEcfhfhARbIGdnFDMSN3tw3Ijy9A0/IJq1tRR8lFXgWtlEq8pZ7y4I3OzKpDhqz/9cIxDlTQdtZnfB0khDhVFDDQx+9rmhjDx01NTy7gcH3BarRUQ7pdTpBVfuJwZh3mMzqQgdKe9Sj1XdKbEz9zLqdE9QWZFx0wkwQQG8W7MrsYPUfOey0hyeFh+xRSICGvOcMeXGrkx/ni0vaQCPxuv2xFYuAK2Cg8ie0W4XPAbfHtMmOG1+L7ecJ4GWUUVCHt/Ljh4/VXEwaj0sCjQlMbzSDd67gfVFQiuYnwcw0="