language: java
jdk:
- oraclejdk8
- oraclejdk7
os:
- linux
branches:
  only:
  - master
  - dev
sudo: required
after_success:
- mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/jacoco/jacoco.xml -DprojectToken=$CODACY_PROJECT_TOKEN -DapiToken=$CODACY_API_TOKEN -DcodacyApiBaseUrl=https://api.codacy.com
env:
  global:
  - secure: "UyI4lTjqJsoHB5tHs1r5/tVl9SKdKATMwH4TUDVLaT6WdFcHrlSn9JuBIk6jXu5PEn9wcNxqGyQ3rf8kUUhGLai9n7M+NGB0ZpQc3HwzAdrBcmWszgFxh+KLMQ7uQULZp4Xo1NMPQL9Au1S51njz0rJkoq49BmeMj1sZc3uode8ZDf3wQjbcspu7CsPU4tSKxIvScsKfv2iNXt5+YZRcrXnM7XsqBGcgGcQEiEzSUd49CMLgbNar3NqeWU1HrKLNrs/wDCTCZkt9VNrUZqd2k6E6LysLTomsFN5nu/uc4Ts5GoQsKDWHA5hM0UwgJ699fRY7OXQ8KTDG9alMhMfCYr0dW94LK4z+G4SNWkGVu+i5wDOizdeQib7iW66072n3nVr5XiF27cE8Dk+N23dxWVVQfvbV7ICFvn0BNm2zV1m/SGL9f5qzpjZYm55NB+N7Vw6YVkpvqiX3PbTVrA="
  - secure: "MwWwZj5qgYvAWHF8SMaJT1kJDTXMPT+s/sTLgQSDOebeM2NKM8mJ7PRwBlj1Y4QhnU31rZZLCVYEdDtVp0VKUMJfnpMgFE222LB8Ca2cvlqEXhjJf3WJCEbDhGq4osch5jE3PRxn4T+OrRbD9ppCQ47CRuKuWA9uBjQh6nDTlRupLy14cQOTtfDJpRCYdyYmhLsgMQqrwbNtWywL1I2lQFFv6Zoy5jop/lMzElyzMewUGX3RuCeaqukt/P0a5lIU3fH/pqM3JTi+vUVN0BmzJAz6xl9PaZIlXM/QA04LfKpY0ipBvxSLfK/6AOXYUwUkwlGvzrQZsW5+W+8VFM0DxE3khbfduh7tMsKGVyRA8yeTsCYFD1USqdUQ2fxNSaIffL4WQsQaTBepB45wcbQLokMr0aE+ezgZu9zWiTlyFkiQa65s1tHQiss0bZ5/RLNumgXzy2t4nyhc5/O0Xknb9Sa1iEJoO+/e1doHrbxeiR20wYbfWZnIEr09YyTcLFWb2ZhRP7i+AZ5Bb555dqRVVR3rMW07U+a7HC6q0KpF6zCLczffDz5TSZmThzXmgdQlfvWcHZmNTZITQVZqd8ozrQ9ua0FUxHvrBXaQO6NPbL4hpGD+ADd7Z+GCpnRrtMtMecqzHyBU5jpB0Q7BSqn2F+xg8yTbQ34GEK3saUHNMQ8="
