language: java
jdk:
- oraclejdk7
- oraclejdk8
os:
- linux
branches:
  only:
  - master
  - dev
sudo: required
before_install:
- mvn org.codehaus.mojo:versions-maven-plugin:display-dependency-updates
- mvn org.codehaus.mojo:versions-maven-plugin:display-plugin-updates
after_success:
- mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/jacoco/jacoco.xml -DprojectToken=$CODACY_PROJECT_TOKEN -DapiToken=$CODACY_API_TOKEN -DcodacyApiBaseUrl=https://api.codacy.com
env:
  global:
  - secure: mO2XZZZEiR1PIR8ZU+gbX3x7yQ4ZaAi9rxMYn3pmJr+OnakJwxt/HVDlHyB5vV/Ef9Z131qWfyb9TG8cRJMlmx2i25GDRuUuYnID5VGjFhD09gPQ1UgMRT3qpiz4n2B3Y9e4SkSBLOBmvdr9ZMaaeh0QNYNbtDwfI4BWiaLqst96y23Bqi//t2yVyqHsGwhJXVR7coR5nB9VBNHZ2A+L7q54ChjG+/ymm3Hvu+faWe209C4fvjAhhLevwDeHqPojRFVOp8dXVjgtXmZ+GAcr1xBrWvJzixeLUPtUZy9WSLi5qqU2pHpMz4TvhIRLLyYDfMzpw4BGDZFvmIM0uDBy/dbyp4MFVdP9+AQZx2FV4vMDoGjLcqKWEkncl8fzz2IWGbUK7e4MUfiBj8L++sddbak+BF7aCXYuYqWfz3mM99em4/I8XzZV67JpoFnvr3O2UY3CZmmTAEn7+xOtIMtPIx0OqTWkkXKY4wsUE3EvU5WqEJ8TxgllHUomoUhrNBnov/uTd3SluDAwtgemio64UfsChLH8eQJUHuWRedBRmrO6JYwAZkuvJy1/5IkRvNsQIIA8079/Nbt8tgGHnHQnBk0asI/1sefAVHAsfPpz+/bIPKc7Gm9ekoXfH8fqAxinfi3uJIXZwX082NMC8cdvdOAv6PJn358PE+bRgzmSaQU=
  - secure: c3+5bR94dWi7wc9qJoSK36olsehUa7ESVwJgYYFP5O3dYPb/VRCMhibsz+Z9zXAQnfqwVvsVHAm3gDCAbqnNsiIRhNj6un8fSRR95Ubi/Zgm/wWBT1BvQ08KIk3da7GYfT8I4x/fZ4TS0h/smihCD346i6t5A6Un84MgsDK8WQWxcBg1GiXPYBwvzYM+Qj25W+3oW1xxk2uYEtEKMTT74cw/1HsYBuCz+b+7Nu/qUIh2J3JvIP5wWQEgpNszOiFZc/EBTMgJuSOluLZydz2mvBC0ogK4fXFqkVFfPsoFrzRrCD/lx/W8wpzqRviEtNQBUL27kaJOa1oR70O3AM8/CUwxraqDaGAiFkF02dxwbdJpCeuHK2iZCmDr7dkemnCCiWMM2ckve4eQShWrfUx0k0N7YvN3UNnO7oBwm1x/ZLS+FKcxVncSXcYN6zpVFs9k2eoOihzm+zvlVbrhaQJFyQIlycCQG0zqCX6ZtVaRwMwd+/jxqC7rhFqNnZo7dwB1YBUC1NWpm5kGrxEcH/NrnCs2rA9bMbtTgFNwZiuZ+QHWbTj8uMW6ALNoTjihVHU4EEqLT2ELYyBkh/dlvcQGA41IPvp8nlqMa/nYw9PBc4ERxK1nMMuFIyRZRdQgaqFOv4rVIUKh4hKgqaNGbH18GUPfFiJ60RlKLmftRygDYks=
